### ISSUE TITLE
Suggestion - Ajout d'un Back to Top sur la page des résultats de recherche

### ISSUE THREAD

**Issue by Sseven-lab** [Julien-Brcht-Rndlt/fridgin-hungry#67]
Comportement actuel :
Lorsqu'on est sur la page de résultats de recherche, que l'on clique sur "View more" ou non, il n'y a pas de moyen de revenir en haut de page pour pouvoir lancer une nouvelle recherche. 

Suggestion : 
Créer un bouton "back-to-top" sur la page des résultats de recherche

**Comment by Julien-Brcht-Rndlt** [comment]
Demande prise en compte.

Feature ajoutée dans prochaine release.
